# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86ddfc6b36ea93b9ca79f7d8395899ad7ed8c0379f318543959fe600853f29f5167458e9d8f9b9932ea690a2d1737eddc3586c4007613ac541ea7ae1ea995c30

test:
  secret_key_base: ecb4bfcd31b9c9be5bee8678b5e518ef571ec6057b1990bc4c01c37e3cd0e64c250251917a6dc821c5f871ee0c9d3dd820c7a878bdf83e32590995dc6d7f841b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
